syntax enable
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=72
set expandtab
set number
set cursorline
filetype indent on
set showmatch
set incsearch
set hlsearch
set autoindent
set mouse=a
